server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mcp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: vanna
    password: vanpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

app:
  db-refresh-interval-ms: 1000

